name: collectionapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  permission_handler: ^11.4.0
  csv: ^6.0.0
  flutter_inappwebview: ^6.0.0 # For displaying HTML invoice in WebView
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  analyzer: ^6.8.0

flutter:
  uses-material-design: true
