name: collectionapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  cupertino_icons: ^1.0.8
  intl: any
  permission_handler: ^11.4.0
  csv: ^6.0.0
  flutter_inappwebview: ^6.1.5
  pdf: ^3.11.3
  universal_html: ^2.2.4
  share_plus: ^10.1.4
  flutter_localizations: # Added from second file
    sdk: flutter
  flutter_gen: ^5.10.0 # Added from second file
  provider: ^6.1.4 # Added from second file

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  analyzer: ^6.8.0
  intl_translation: ^0.20.0 # Added from second file
  intl_utils: ^2.8.5 # Added from second file
  flutter_gen_runner: ^5.3.2 # Added from second file

flutter:
  uses-material-design: true
  generate: true # Added from second file
  assets:
    - assets/images/logo.png # Explicitly included from first file

